import Link from "next/link";
import { Activity, ArrowUpRight, BarChart3, MousePointerClick, Target } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { getWorkspaceForUser } from "@/lib/workspace";
import { money, number, percent } from "@/lib/format";

export default async function DashboardPage() {
  const user = await requireUser(); const { workspace } = await getWorkspaceForUser(user.id);
  const since = new Date(); since.setDate(since.getDate() - 30);
  const [clicks, unique, conversions, campaigns] = await Promise.all([
    db.clickEvent.count({ where: { workspaceId: workspace.id, occurredAt: { gte: since } } }),
    db.clickEvent.groupBy({ by: ["visitorHash"], where: { workspaceId: workspace.id, occurredAt: { gte: since }, visitorHash: { not: null } } }),
    db.conversionEvent.count({ where: { workspaceId: workspace.id, occurredAt: { gte: since } } }),
    db.campaign.findMany({ where: { workspaceId: workspace.id }, orderBy: { createdAt: "desc" }, take: 5 }),
  ]);
  const spend=campaigns.reduce((sum,campaign)=>sum+Number(campaign.spend),0); const revenue=campaigns.reduce((sum,campaign)=>sum+Number(campaign.revenue),0);
  const metrics=[["Clics",number(clicks),"30 derniers jours"],["Visiteurs uniques",number(unique.length),"Estimation respectueuse"],["Conversions",number(conversions),"Événements attribués"],["Taux de conversion",percent(clicks?conversions/clicks:0),"Conversions / clics"],["ROAS",spend?`${(revenue/spend).toFixed(2)}×`:"—",`${money(revenue,workspace.currency)} attribués`]];
  return <><div className="page-header"><div><h2>Bonjour {user.name.split(" ")[0]}</h2><p>Voici l’état de votre performance publicitaire.</p></div><div className="filters"><button className="filter-pill">Aujourd’hui</button><button className="filter-pill">7 jours</button><button className="filter-pill active">30 jours</button><button className="filter-pill">Personnalisé</button></div></div><section className="metric-grid">{metrics.map((metric,index)=><article className="metric-card" key={metric[0]}><span>{metric[0]}</span><strong>{metric[1]}</strong><small className={index===4?"trend":"trend neutral"}>{metric[2]}</small></article>)}</section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><h3>Clics et conversions</h3><span>Évolution sur la période</span></div><Activity size={17}/></div>{clicks===0?<Empty icon={<BarChart3/>} title="Vos données apparaîtront ici" text="Créez une campagne et partagez votre premier lien de tracking pour commencer." href="/app/campagnes/nouvelle"/>:<p>{clicks} clics et {conversions} conversions collectés.</p>}</article><article className="panel"><div className="panel-head"><div><h3>Sources de trafic</h3><span>Répartition des clics</span></div><MousePointerClick size={17}/></div>{clicks===0?<Empty icon={<MousePointerClick/>} title="Aucune source détectée" text="Les paramètres UTM identifieront automatiquement vos canaux." href="/app/liens/nouveau"/>:<p>{clicks} événements collectés.</p>}</article></section><section className="panel campaign-panel"><div className="panel-head"><div><h3>Campagnes récentes</h3><span>Performance de vos dernières campagnes</span></div><Link href="/app/campagnes">Voir tout <ArrowUpRight size={14}/></Link></div>{campaigns.length===0?<Empty icon={<Target/>} title="Créez votre première campagne" text="Définissez un objectif, un canal et un budget pour structurer votre suivi." href="/app/campagnes/nouvelle"/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Campagne</th><th>Canal</th><th>Statut</th><th>Dépenses</th><th>Revenus</th></tr></thead><tbody>{campaigns.map(campaign=><tr key={campaign.id}><td><Link href={`/app/campagnes/${campaign.id}`}><strong>{campaign.name}</strong></Link></td><td>{campaign.channel}</td><td><span className={`badge ${campaign.status.toLowerCase()}`}>{campaign.status}</span></td><td>{money(Number(campaign.spend),campaign.currency)}</td><td>{money(Number(campaign.revenue),campaign.currency)}</td></tr>)}</tbody></table></div>}</section></>;
}
function Empty({icon,title,text,href}:{icon:React.ReactNode;title:string;text:string;href:string}){return <div className="empty"><span className="empty-icon">{icon}</span><h3>{title}</h3><p>{text}</p><Link className="btn secondary small" href={href}>Commencer</Link></div>}
