import Link from "next/link";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDollarSign, Gauge, Globe2, Link2, MousePointerClick, Route, ShieldCheck, Sparkles, Target, Workflow, Zap } from "lucide-react";
import { Footer } from "@/components/footer";
import { PublicNav } from "@/components/public-nav";
import { db } from "@/lib/db";

const features = [
  { icon: MousePointerClick, title: "Tracking précis", text: "Suivez chaque clic utile, ses paramètres UTM, sa source, son appareil et son parcours — sans collecter plus de données que nécessaire." },
  { icon: Target, title: "Attribution claire", text: "Reliez campagnes, liens et conversions pour identifier les investissements qui créent vraiment du chiffre d’affaires." },
  { icon: Route, title: "Routage intelligent", text: "Dirigez automatiquement chaque visiteur vers la meilleure page selon son appareil, son pays ou sa source." },
  { icon: BarChart3, title: "Analyses actionnables", text: "CPC, CPA, ROAS et ROI réunis dans des tableaux de bord conçus pour décider vite." },
  { icon: Workflow, title: "Automatisations", text: "Créez des alertes basées sur vos seuils de performance et préparez les actions automatisées de demain." },
  { icon: ShieldCheck, title: "Données maîtrisées", text: "Isolation par espace, sessions sécurisées, contrôles d’accès et journal d’audit intégrés dès la fondation." },
];

const plans = [
  { name: "Essai gratuit", price: "0 €", description: "Pour découvrir ADPulse avec vos premières campagnes.", items: ["14 jours d’essai", "1 espace de travail", "1 000 clics suivis", "Analyses essentielles"], cta: "Commencer gratuitement" },
  { name: "Starter", price: "Sur demande", description: "Pour les indépendants et petites équipes en croissance.", items: ["Campagnes et liens illimités", "Routage intelligent", "Conversions et alertes", "Support standard"], cta: "Créer mon compte", featured: true },
  { name: "Pro", price: "Sur demande", description: "Pour les équipes qui pilotent plusieurs canaux.", items: ["Volumes étendus", "Intégrations publicitaires", "Automatisations avancées", "Support prioritaire"], cta: "Parler à l’équipe" },
];

export const dynamic = "force-dynamic";
export default async function Home() {
  const configured = await db.plan.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } }).catch(() => []);
  const visiblePlans = configured.length ? configured.map((plan, index) => ({ name: plan.name, price: Number(plan.price) === 0 ? "Gratuit" : new Intl.NumberFormat("fr-FR", { style: "currency", currency: plan.currency, maximumFractionDigits: 0 }).format(Number(plan.price)) + (plan.billingInterval === "MONTH" ? "/mois" : "/an"), description: plan.description ?? "Une offre ADPulse adaptée à vos objectifs.", items: Array.isArray(plan.features) ? plan.features.map(String).slice(0, 5) : [], cta: plan.trialDays > 0 ? "Commencer gratuitement" : "Choisir cette offre", featured: index === 1 })) : plans;
  return <><PublicNav /><main>
    <section className="hero"><div className="hero-glow" /><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15} /> L’intelligence publicitaire, enfin exploitable</div><h1>Transformez chaque clic en <span>meilleure décision.</span></h1><p>ADPulse centralise le tracking, l’attribution et la performance de vos campagnes. Voyez ce qui convertit, corrigez ce qui coûte, accélérez ce qui fonctionne.</p><div className="hero-actions"><Link className="btn primary large" href="/inscription">Démarrer gratuitement <ArrowRight size={18} /></Link><Link className="btn secondary large" href="#produit">Découvrir la plateforme</Link></div><div className="trust-row"><span><Check size={16} /> Sans carte bancaire</span><span><Check size={16} /> Configuration rapide</span><span><Check size={16} /> Données isolées</span></div></div><div className="hero-visual" aria-label="Aperçu du tableau de bord ADPulse"><div className="visual-top"><div><span className="dot red"/><span className="dot amber"/><span className="dot green"/></div><span>Vue d’ensemble</span><span>7 derniers jours</span></div><div className="mini-metrics"><div><span>Dépenses</span><strong>4 820 €</strong><small>Budget maîtrisé</small></div><div><span>Revenus attribués</span><strong>18 492 €</strong><small className="positive">+18,4 %</small></div><div><span>ROAS</span><strong>3,84×</strong><small className="positive">+0,62</small></div></div><div className="chart-card"><div className="chart-head"><div><strong>Performance</strong><span>Dépenses et revenus attribués</span></div><div className="legend"><span><i className="blue"/>Revenus</span><span><i className="violet"/>Dépenses</span></div></div><svg viewBox="0 0 620 210" role="img" aria-label="Courbes de revenus et dépenses"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4767ff" stopOpacity=".22"/><stop offset="1" stopColor="#4767ff" stopOpacity="0"/></linearGradient></defs><path className="gridline" d="M15 30H605M15 85H605M15 140H605M15 195H605"/><path fill="url(#area)" d="M15 168 C70 155 92 167 140 132 S218 124 264 92 S342 115 390 72 S470 78 514 45 S570 48 605 25 V195 H15Z"/><path className="line-primary" d="M15 168 C70 155 92 167 140 132 S218 124 264 92 S342 115 390 72 S470 78 514 45 S570 48 605 25"/><path className="line-secondary" d="M15 178 C75 171 98 176 145 158 S220 161 268 143 S338 151 390 126 S468 139 515 112 S570 124 605 99"/></svg></div><div className="source-strip"><span>Meilleurs canaux</span><div><i className="meta">M</i><b>Meta Ads</b><small>2,9× ROAS</small></div><div><i className="google">G</i><b>Google Ads</b><small>4,2× ROAS</small></div><div><i className="organic">O</i><b>Organique</b><small>38 % conv.</small></div></div></div></div></section>
    <section className="logo-band"><div className="container"><p>Une vision unifiée de vos canaux d’acquisition</p><div><span>Meta Ads</span><span>Google Ads</span><span>TikTok</span><span>Mobile Money</span><span>Sites & landing pages</span></div></div></section>
    <section id="produit" className="section"><div className="container"><div className="section-head"><div><span className="kicker">TOUTE VOTRE PERFORMANCE, AU MÊME ENDROIT</span><h2>Du trafic à la conversion, sans angle mort.</h2></div><p>ADPulse donne à votre équipe une lecture cohérente de chaque campagne, du premier clic au revenu attribué.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }) => <article className="feature-card" key={title}><span className="icon-box"><Icon size={23} /></span><h3>{title}</h3><p>{text}</p><Link href="/inscription">Explorer <ChevronRight size={16}/></Link></article>)}</div></div></section>
    <section id="solutions" className="section tinted"><div className="container split"><div className="product-shot"><div className="shot-bar"><strong>Campagnes</strong><span>+ Nouvelle campagne</span></div>{[["Retargeting Q4","Meta Ads","ACTIVE","3,92×"],["Acquisition Search","Google Ads","ACTIVE","4,48×"],["Lancement Abidjan","TikTok","PAUSE","2,16×"]].map(row=><div className="campaign-row" key={row[0]}><span className="campaign-icon"><Gauge size={18}/></span><div><strong>{row[0]}</strong><small>{row[1]}</small></div><em className={row[2] === "ACTIVE" ? "active" : "paused"}>{row[2]}</em><b>{row[3]}<small>ROAS</small></b></div>)}</div><div className="split-copy"><span className="kicker">PILOTAGE MULTICANAL</span><h2>Comprenez vos campagnes. Agissez au bon moment.</h2><p>Comparez les canaux avec les mêmes indicateurs. ADPulse vous alerte dès qu’un coût dérape, qu’un lien échoue ou qu’une opportunité apparaît.</p><ul className="check-list"><li><Check/> Attribution par campagne et par lien</li><li><Check/> Alertes CPA, ROAS et conversion</li><li><Check/> Historique d’activité et journal d’audit</li><li><Check/> Connexion Meta Ads préparée et sécurisée</li></ul><Link className="text-link" href="/inscription">Voir comment ADPulse vous aide <ArrowRight size={17}/></Link></div></div></section>
    <section className="section"><div className="container"><div className="center-head"><span className="kicker">SIMPLE À LANCER</span><h2>Trois étapes pour retrouver le contrôle.</h2></div><div className="steps">{[["01","Créez vos campagnes","Structurez vos objectifs, budgets, canaux et paramètres UTM."],["02","Diffusez vos liens","Générez des liens courts et appliquez vos règles de routage."],["03","Optimisez avec les faits","Suivez conversions, coûts et revenus dans une vue unifiée."]].map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>
    <section className="section dark"><div className="container usecases"><div><span className="kicker light">CONÇU POUR LA PERFORMANCE</span><h2>Une plateforme. Plusieurs façons de grandir.</h2></div><div className="usecase-grid"><article><Globe2/><h3>Agences</h3><p>Isolez les données de chaque espace et standardisez vos rapports de campagne.</p></article><article><CircleDollarSign/><h3>E-commerce</h3><p>Reliez les achats au bon canal et suivez votre revenu publicitaire.</p></article><article><Zap/><h3>Équipes growth</h3><p>Testez des destinations, mesurez les résultats et automatisez les alertes.</p></article><article><Link2/><h3>Créateurs & affiliés</h3><p>Organisez vos liens, vos sources et vos conversions sans tableurs dispersés.</p></article></div></div></section>
    <section id="tarifs" className="section"><div className="container"><div className="center-head"><span className="kicker">DES OFFRES QUI ÉVOLUENT AVEC VOUS</span><h2>Commencez simplement. Passez à l’échelle sereinement.</h2><p>Les tarifs et limites définitifs sont administrables dans ADPulse et adaptés à votre marché.</p></div><div className="pricing-grid">{visiblePlans.map(plan=><article className={`price-card ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <span className="popular">Le plus choisi</span>}<h3>{plan.name}</h3><strong>{plan.price}</strong><p>{plan.description}</p><Link className={`btn ${plan.featured ? "primary" : "secondary"}`} href="/inscription">{plan.cta}</Link><ul>{plan.items.map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul></article>)}</div></div></section>
    <section id="faq" className="section faq-section"><div className="container faq-grid"><div><span className="kicker">QUESTIONS FRÉQUENTES</span><h2>Tout ce qu’il faut savoir avant de commencer.</h2><p>Vous avez une question spécifique ? <a href="mailto:contact@getadpulse.tech">Écrivez-nous.</a></p></div><div>{[["ADPulse remplace-t-il mes plateformes publicitaires ?","Non. ADPulse réunit leurs données de performance, ajoute le tracking et vous aide à piloter vos décisions depuis un même espace."],["Puis-je suivre des conversions sur mon site ?","Oui. L’API de conversion permet de remonter les événements page vue, lead, inscription, achat ou tout événement personnalisé."],["Mes données sont-elles séparées de celles des autres clients ?","Oui. Toute lecture et écriture métier est rattachée à un espace de travail avec contrôle d’accès par rôle."],["Quels moyens de paiement seront disponibles ?","L’architecture accepte plusieurs prestataires, dont Mobile Money et les cartes. L’administrateur active les passerelles configurées pour son marché."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
    <section className="cta-section"><div className="container cta-card"><div><span className="eyebrow dark-eye">Votre prochaine décision commence ici</span><h2>Passez du suivi dispersé à une performance maîtrisée.</h2><p>Créez votre espace ADPulse et donnez enfin à chaque campagne le contexte qu’elle mérite.</p></div><Link className="btn white large" href="/inscription">Créer mon espace <ArrowRight size={18}/></Link></div></section>
  </main><Footer /></>;
}
