import Link from "next/link";
import { BarChart3, Bell, Bot, CircleDollarSign, Gauge, HelpCircle, LayoutDashboard, Link2, Megaphone, Menu, Settings, Shield } from "lucide-react";
import { Brand } from "./brand";
import { LogoutButton } from "./logout-button";

export function AppShell({user,workspace,isAdmin,children}:{user:{name:string;email:string};workspace:{name:string};isAdmin:boolean;children:React.ReactNode}){
 const nav=[["/app",LayoutDashboard,"Vue d’ensemble"],["/app/campagnes",Megaphone,"Campagnes"],["/app/liens",Link2,"Liens de tracking"],["/app/analytics",BarChart3,"Analytics"],["/app/automatisations",Bot,"Automatisations"],["/app/facturation",CircleDollarSign,"Facturation"]] as const;
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="workspace-switch"><span>{workspace.name.slice(0,1).toUpperCase()}</span><div><strong>{workspace.name}</strong><small>Espace de travail</small></div></div><nav className="side-nav"><span className="side-label">Pilotage</span>{nav.map(([href,Icon,label])=><Link href={href} key={href}><Icon size={16}/>{label}</Link>)}<span className="side-label">Configuration</span><Link href="/app/integrations"><Gauge size={16}/>Intégrations</Link><Link href="/app/parametres"><Settings size={16}/>Paramètres</Link>{isAdmin&&<Link href="/admin"><Shield size={16}/>Administration</Link>}</nav><div className="side-bottom"><Link href="/aide" className="side-help"><HelpCircle size={15}/> Centre d’aide</Link><LogoutButton/><div className="user-tile"><span className="avatar">{user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div></div></aside><div className="app-main"><header className="app-topbar"><button className="icon-btn mobile-menu" aria-label="Ouvrir le menu"><Menu size={18}/></button><h1>ADPulse</h1><div className="app-tools"><button className="icon-btn" aria-label="Notifications"><Bell size={16}/></button><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span></div></header><main className="app-content">{children}</main></div></div>
}
